laravel/livewire-starter-kit

resources/views/components/layouts/app/header.blade.php, resources/views/components/layouts/app/sidebar.blade.php, resources/views/components/layouts/auth/card.blade.php, resources/views/components/layouts/auth/simple.blade.php, resources/views/components/layouts/auth/split.blade.php
This PR adds the missing `wire:navigate` attributes to the hyperlinks, preventing full page reloads by enabling Livewire navigation.
=> Add the missing 'wire:navigate' attributes

resources/views/components/action-message.blade.php
fix "Saved" text color on action-message.blade.php component
before
after
=> Update text color on action-message.blade.php

resources/views/components/layouts/app/header.blade.php, resources/views/components/layouts/app/sidebar.blade.php, resources/views/components/settings/layout.blade.php, resources/views/livewire/settings/appearance.blade.php, resources/views/livewire/settings/password.blade.php, resources/views/livewire/settings/profile.blade.php, resources/views/partials/settings-heading.blade.php
This PR addresses a similar issue to [laravel/breeze#215](https://github.com/laravel/breeze/pull/215).  
Some of the new Livewire Starter Kit Blade files were missing translation methods, and this PR fixes them.
=> Add missing translation methods to Livewire stack

resources/views/dashboard.blade.php
Minor tweak to hide overflowing pattern through the border.
**Before**
**After**
Love your work!
👌
=> fix pattern overflow on placeholder

resources/views/components/text-link.blade.php, resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php
This removes the custom `x-text-link` blade component in favor of using the **free** `flux:link` component.
And therefore removes unnecessary complexity.
=> Using `flux:link` component instead of custom `text-link` blade component

resources/views/livewire/auth/login.blade.php
When the register route has been disabled (to stop random signups) you then can't log in as the login form fails before it is rendered.
This PR fixes that.
=> Add check for register route in case registrations have been disabled

resources/views/livewire/auth/verify-email.blade.php, resources/views/livewire/settings/profile.blade.php
This PR changes default HTML button tags that looks like links to `flux:link` without a href attribute.
Also added hover effect to change the cursor to pointer.
Because we don't have a href attribute but a `wire:click` attribute, this link acts like a button instead of a link, but looks like a link.
Refrences;
Dark and light mode, the top "log out" button is the new one.
Before:
After:
=> Changed default button tags to be `flux:link` tags

resources/views/components/auth-header.blade.php, resources/views/components/layouts/auth/split.blade.php, resources/views/livewire/auth/verify-email.blade.php, resources/views/livewire/settings/profile.blade.php
This PR changes default HTML tags to flux tags like; `flux:heading` `flux:subheading` `flux:text`
This fixes issues with themes and dark mode, and keeps the whole website consistent!
We should avoid using default paragraph and heading tags with TailwindCSS calasses on them, as much as possible to not break themes and darkmode.
=> Changed standard HTML tags with flux tags

resources/views/livewire/auth/confirm-password.blade.php, resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php, resources/views/livewire/auth/reset-password.blade.php, resources/views/livewire/settings/appearance.blade.php, resources/views/livewire/settings/delete-user-form.blade.php, resources/views/livewire/settings/password.blade.php, resources/views/livewire/settings/profile.blade.php
I think it's better to use the colon syntax for translations. If you agree, I'll proceed with the rest of the files...
`heading="{{ __('Appearance') }}"`
vs
`:heading="__('Appearance')"`
=> Fix Blade binding: use colon syntax for props with translations

resources/views/livewire/auth/confirm-password.blade.php, resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php, resources/views/livewire/auth/reset-password.blade.php, resources/views/livewire/settings/delete-user-form.blade.php, resources/views/livewire/settings/password.blade.php, resources/views/livewire/settings/profile.blade.php
Removes attributes on the `flux:input` component which are not used, like `id` and `name`.
This makes the code more readable and easier to maintain.
=> Removes unused `flux:input` attributes

resources/views/livewire/auth/register.blade.php
Currently, if a user attempts to access an authentication-protected resource without being logged in, they are redirected to the login page. After logging in, they are correctly redirected to the intended URL.
However, if the user doesn’t have an account and chooses to sign up instead, they are redirected to the dashboard route after registration, rather than the URL they initially intended to visit. This results in an inconsistent user experience, requiring manual navigation to the desired page after signing up.
This PR updates the registration component to ensure that users are redirected to their intended URL after completing the sign-up process.
=> Redirect to intended URL after registration

resources/views/livewire/auth/confirm-password.blade.php, resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php, resources/views/livewire/auth/reset-password.blade.php
As @tnylea mentioned earlier (https://github.com/laravel/livewire-starter-kit/pull/28#issuecomment-2685148846), some translations are still missing. My previous PR included all the missing translations but wasn't merged, so I recreated it to address this.
=> Add missing translations

resources/views/components/layouts/app.blade.php, resources/views/components/layouts/app/sidebar.blade.php, resources/views/dashboard.blade.php
Adds `title` prop to `dashboard` view, `components.layout.app` & `components.layout.app.sidebar` which then sets the title variable in `partials.head`.
It's a bit confusing on first use how to set the title of the page. At the moment it just displays 'Laravel' and is hardcoded. With this it makes it the dashboard's title 'Dashboard' so that users can quickly resolve it.
=> Passes the title down to the head view

tests/Feature/Auth/AuthenticationTest.php
The post `/login` path does not exist, currently this test is reporting a 405 Method Not Allowed error.
Modified to test the actual code within the Livewire component.
I saw this issue because I copied this test in order to create one hitting the rate limiter, and it was not working. 😅
----
The non Volt version has the same issue, I'll make a PR to that branch too.
=> Fix test `users_can_not_authenticate_with_invalid_password`

tests/Feature/Auth/AuthenticationTest.php
Same as #64 targeting `components` branch.
=> Fix test `users_can_not_authenticate_with_invalid_password` (Components branch)

.github/workflows/lint.yml
I’ve been trying to use the ‘Commit Changes’ step from the Lint Action, but it always fails when I run it. 
I’ve attached a change suggestion that should fix this issue.
=> fix: Commit step -- replace file_pattern expression

README.md
Hi,
I wanted to contribute some changes to this Starter Kit, but realized I was looking at the `main` branch's Volt-specific code. I had decided not to use Volt locally, so my code looked different.  It took some digging to figure out that the alternate configurations are just different branches on this repo. Makes sense, but hard to find unless you know where to look.  This may also help contributors understand that they may want to fork the entire repo rather than just `main`.
Hope this helps, and if you have any stylistic feedback or other info to add, feel free to edit.  I hope this sort of thing can be published rather than obfuscated.
=> Update README to describe configuration variant working trees

resources/css/app.css
This issue was brought up in the FluxUI repo: https://github.com/livewire/flux/issues/1320,
We have added the:
```
[data-flux-field] {
@apply grid gap-2;
}
```
to input fields in flux so that way the login/register forms are more consistent with the React and Vue versions; unfortunately applying `grid` to the Radio card causes this issue.
This update will fix that issue.
=> fixing layout issue where grid does not work with the UI radio element

vite.config.js
This PR will add the default refresh directories back to the Livewire Starter kit.
This will revert the defaults for a Livewire application and will watch for changes in the following directories:
```
'app/Livewire/**',
'app/View/Components/**',
'lang/**',
'resources/lang/**',
'resources/views/**',
'routes/**',
```
=> Adding default hot reloading/refreshing back to the vite config

resources/views/livewire/auth/confirm-password.blade.php, resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php, resources/views/livewire/auth/reset-password.blade.php
Flux allows you to make password inputs viewable (by clicking a little eyeball icon) by simply adding a `viewable` attribute, which is pretty amazing when you think about it! This PR adds the `viewable` attribute to the flux password inputs.
https://fluxui.dev/components/input#clearable-copyable-and-viewable-inputs
=> Makes flux password inputs viewable

composer.json
When running `composer run dev`, the [concurrently](https://www.npmjs.com/package/concurrently) package is used to start multiple processes in one terminal. This is a great addition to the Laravel starter kits! However, when sending the EXIT signal (CTRL + C) only the last process in the configured list is closed. 
By adding the **--kill-others** option to the command, **all** the related processes are closed.
I would add this flag in by default, as the current behaviour is most likely unintended. For example, in case you are switching projects and need the ports released for re-use, you now need to manually find the other processes and close them yourself.
This change was already approved in the Vue starter kit: https://github.com/laravel/vue-starter-kit/pull/123
=> Making sure all related processed are closed when terminating the currently command

resources/views/livewire/auth/forgot-password.blade.php
There is a "viewable" attribute on the email input which is redundant as the field type isn't password. This removes that attribute.
=> chore(views): remove redundant `viewable` attribute from email input

resources/views/livewire/auth/forgot-password.blade.php, resources/views/livewire/auth/login.blade.php, resources/views/livewire/auth/register.blade.php
The span tags was added to correct the spacing between elements. 
Without it the parent .space-x-1 class doesn't work.
=> Fix: Adding missing span tags to correct spacing 

package-lock.json, package.json
- Upgrade Vite from v6.2.0 to v7.0.4
- Upgrade Laravel Vite Plugin from v1.0 to v2.0.0
- Latest Vite features and performance improvements
- Better compatibility with modern build tools
- Enhanced development experience with faster builds
=> Upgrade Vite to v7

app/Livewire/Auth/ResetPassword.php
The `request()->string('email')` method returns an `Illuminate\Support\Stringable` object, which causes a TypeError `Cannot assign Illuminate\Support\Stringable to property App\Livewire\Auth\ResetPassword::$email of type string` when using `declare(strict_types=1)`, which most of us (presumably) use.
Added `->value()` to convert the Stringable object to a plain string value.
=> Fix: Convert Stringable to string for email property

database/factories/UserFactory.php, tests/Feature/Auth/AuthenticationTest.php, tests/Feature/Settings/TwoFactorAuthenticationTest.php
This PR resolves a failing test in TwoFactorAuthenticationTest.php when running with Model::shouldBeStrict() enabled because of unavailable attributes.
=> Refactor the UserFactory to include withoutTwoFactor method
